version: '3'

services:
  chatgpt_telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_TELEGRAM_USERNAMES=${ALLOWED_TELEGRAM_USERNAMES}
      - BOT_LANGUAGE=${BOT_LANGUAGE:-en}
      - CHAT_MODE=${CHAT_MODE:-chat}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-chatgpt_telegram_bot}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
    depends_on:
      - mongodb
    volumes:
      - ./config:/app/config
      # For convenience, make sqlite database persistent
      - ./:/app 

  mongodb:
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/db:/data/db
    command: mongod --logpath=/dev/null
    logging:
      driver: none
    ports:
      - 27017:27017